### ISSUE TITLE
Add Package "ok"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1110]
Add the Package "ok" from hex.pm

Link: https://hex.pm/packages/ok

Description:

**Comment by CrowdHailer** [comment]
Now that this package has had a 1.0 release I would be happy to say it's probably awesome.

I have added clear documentation and links to several related projects for context

**Comment by bill-mybiz** [comment]
I've been using OK's happy pipe operator (`~>>`) in production on ibgib (e.g. [here](https://github.com/ibgib/ibgib/blob/master/ib_gib_umb/apps/ib_gib/lib/ib_gib/transform/plan/factory.ex#L25))and it cleans up the code nicely. I've also started to use `OK.with` such as:

```
OK.with do
  query_ib_gib <- get_query_ib_gib(query_result_info[:rel8ns]["query"])
  query <- IbGib.Expression.Supervisor.start_expression(query_ib_gib)
  query_info <- query |> get_info()
  refresh(:query, identity_ib_gibs, query_ib_gib, query, query_info)
end
```
I think this is really sweet:
* It _concisely_ conveys that it is an `:ok/:error` block and that it is a `with` statement (i.e. a happy path).
* It eliminates the happy/error path noise, making it more readable and gaining horizontal real estate.
  * This is important for me, because naming things is hard and I use longer names in functions, vars, etc. to explicitly describe things.
* It avoids the use of commas separating statements.
  * I use `with` constructs a lot, and I'm always copy pasting lines, debug logging, etc., and I get compile errors because of a misplaced or missing comma. It's an easy fix, but they definitely accumulate.

Overall, I think it's an awesome lib. :+1:

**Comment by CrowdHailer** [comment]
@bill-mybiz Thanks to the vote of confidence
