### ISSUE TITLE
Turn of that bot!

### ISSUE THREAD

**Issue by NobbZ** [h4cc/awesome-elixir#1682]
It seems that there is some kind of bot running somewhere that does add an issue for every newly created package at hex.pm.

I do see several problems with this behaviour:
- hex.pm is **not** exclusively used for elixir but for every language that targets `beam`-VM
- Many of the issues added by the bot seem to simply be very early or even empty releases to reserve the name
- If everything is added here anyway, we can better stick with hex.pm, because it is easier searchable.

"curated list" means, at least in my opinion, that humans decide what shall be on that list. I'd prefer if the flow were like the following:
1. A user searches for a package solving his problem on this list, but doesn't find anything.
2. Then he searches hex.pm and
   - finds something and uses it
   - finds nothing and implements something by himself
3. He is happy with what he is using
4. He does suggest to add that package into this awesome list.

This is the flow as it is used by nearly every other awesome-list I'm aware of and it works very well, while we do have a pile of open issues no one seems to care about.

Currently there are 668 open issues, created by that account that runs the suspicious bot, while there are only 2 Pullrequests. None of them are related to any of the issues created by the bot. This ratio should be a signal, that it can't continue like this.

**Comment by h4cc** [comment]
Yes there is a automatism running, simply a Zapier Zap using the Hex API. Before that, i added a RSS feed to hex_web to do this (https://github.com/hexpm/hex_web/pull/29).

I cant see why such a automatism is "suspicious" or problematic in any kind, because:

* Anything compatible with BEAM is interesting for elixir and erlang users.
* Very early packages ain't a problem in such a young ecosystem like elixir has. The idea is what counts.
* As you can see, not "everything is added here anyway". And it was stated by @ericmj , that hex should __not__ be a community site, just a package manager. There are already pages like http://toolbox.elixir.pm/ by @henrik starting to provide a community character.

Avery package in this list was added by hand, and it will most likely stay that way.

This lists started, when there where < 100 packages on hex and people new to elixir needed a place to find stuff quickly. Back then it was the easiest way for me to support a young programming language without coding.

If you like to work the way you prefer, do so. I don't think about dictating any ways of working, except a few basic rules in here: https://github.com/h4cc/awesome-elixir/blob/master/CONTRIBUTING.md

I don't really care how other lists do their "work". Beside the fact that this kind of knowledge management does not scale well and needs a lot of effort. In some time in the future this list will be obsolete and i am aware of that.

This is not a development project, it is a community-driven collection. So any metrics about issue/Pull-request ratio does not apply here.

The way it went and is going now is fine with me and nobody is harmed by this. As long as this is fulfilled it will stay.
