### ISSUE TITLE
Add Package "tally"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2148]
Add the Package "tally" from hex.pm

Link: https://hex.pm/packages/tally

Description: 
A reporting library for Elixir

**Comment by KaySackey** [comment]
Tally is a wrapper around 4-5 functions in the Enum/List standard library. It's core is 40 lines long, and consists mostly of setup for a Macro. It has no documentation, and no examples apart from its test code.

I really like awesome-elixir because it shows off *awesome* libraries, but adding stuff like this is akin to making the readme a categorized listing of hex.pm
