### ISSUE TITLE
Evaluate Package "toolbelt"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3875]
Evaluate "toolbelt" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/toolbelt

Description: 
A library for some common and less common Elixir routines not found in the standard library.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by samvv** [comment]
I am the author of toolbelt, and it would be very awesome indeed if it were to be in the list. It aims to be a standard tool for performing routines where you'd normally use something like an `Util` module, and its design is somewhat different from [mykewould/crutches](https://github.com/mykewould/crutches). Because of this, I think it is (or will become) a viable alternative.
