### ISSUE TITLE
Evaluate Package "ease"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3883]
Evaluate "ease" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/ease

Description: 
Simple implementation of standard animation easing functions.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by nicholasgriffen** [comment]
Recommendation: 
Do not include
Data: 
Downloads since latest hex publish ( Sep 4, 2018 ) 
- 170
Latest code commit Age:
- 7 months 
Latest code commit: 
- Message: "Update dependencies so the build passes" 
- Source: https://gitlab.com/jimsy/ease.ex/-/commit/58f89f9088e9e17dc458ebbe97961ddf24430a72
