### ISSUE TITLE
Evaluate Package "saul"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#4011]
Evaluate "saul" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/saul

Description: 
Data validation and conformation library for Elixir.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by acconrad** [comment]
I took a look at this package and it's pretty robust and neat, but hasn't been developed since it was released, my guess is that no one has put up issues simply due to lack of exposure. Seems like it could be a nice complement to the validators that Phoenix uses, either to augment a Phoenix app or to provide basic validation for Elixir (non-web, non-Phoenix) apps.

**Comment by h4cc** [comment]
Thats quite fitting. Another good underlooked package by @whatyouhide  :)

**Comment by whatyouhide** [comment]
There's been little development in Saul because I was working on property-based testing in [stream_data](https://github.com/whatyouhide/stream_data) and we have plans to experiment how the two libraries could provide some kind of joint functionality akin to something like clojure.spec does. The library is hopefully stable-ish though so that's why I haven't worked actively on it in a while :).
