### ISSUE TITLE
Abandoned packages in the list

### ISSUE THREAD

**Issue by savonarola** [h4cc/awesome-elixir#4325]
Hello! 

There are really *lots* of packages in the list which are abandoned for several years (have no commits since several years ago), like [lhttpc](https://github.com/talko/lhttpc) which targets Erlang/OTP R13-B.

The README format also does not allow to see any information about, say, number of stars or days since last commit for the listed repos. As time passes, newcomers can be more disappointed with such abandoned libraries.

Are there any plans to do something with the abandoned items to keep the list awesome? Like:
* evaluating libraries for compatibility with the mainstream versions of Erlang/Elixir
* moving outdated libraries to a special section
* removing them from the list
* ...?

**Comment by mindseyeblind** [comment]
In the one year since this issue was last active, this problem has only gotten worse. For instance, lhttpc has not been updated in over 4 years - since May 2014. A large fraction of this list consists of unusable & abandoned packages.

Some egregious offenders, with their time of last update:

## Actors
* [pool_ring](https://github.com/camshaft/pool_ring) - Jun 2015
* [pooler](https://github.com/seth/pooler) - Jun 2016
* [workex](https://github.com/sasa1977/workex) - May 2016

## Algorithms and Data structures
*Libraries and implementations of algorithms and data structures.*

* [array](https://github.com/takscape/elixir-array) - Sep 2014
* [aruspex](https://github.com/dkendal/aruspex) - Jul 2016
* [blocking_queue](https://github.com/joekain/BlockingQueue) - Oct 2016
* [count_buffer](https://github.com/camshaft/count_buffer) - Dec 2015
* [cuid](https://github.com/duailibe/cuid) - May 2015
* [dlist](https://github.com/stocks29/dlist) - Mar 2015
* [elistrix](https://github.com/tobz/elistrix) - May 2015
* [ezcryptex](https://github.com/stocks29/ezcryptex) - Jul 2015
* [gen_fsm](https://github.com/pavlos/gen_fsm) - May 2016
* [graphmath](https://github.com/crertel/graphmath) - Jul 2016
* [hash_ring_ex](https://github.com/reset/hash-ring-ex) - Nov 2016
* [lfsr](https://github.com/pma/lfsr) - Nov 2016
* [luhn](https://github.com/ma2gedev/luhn_ex) - Mar 2016
* [natural_sort](https://github.com/DanCouper/natural_sort) - May 2015
* [navigation_tree](https://github.com/gutschilla/elixir-navigation-tree) - Sep 2015
* [parex](https://github.com/StevenJL/parex) - Jul 2015
* [simhash](https://github.com/UniversalAvenue/simhash-ex) - Jul 2016
* [sorted_set](https://github.com/SenecaSystems/sorted_set) - Jul 2015
* [spacesaving](https://github.com/rozap/spacesaving) - Apr 2016
* [structurez](https://github.com/hamiltop/structurez) - Sep 2015
* [supermemo](https://github.com/edubkendo/supermemo) - Nov 2014
* [tfidf](https://github.com/OCannings/tf-idf) - Aug 2015
* [zipper_tree](https://github.com/Dkendal/zipper_tree) - Feb 2015

To be continued.

**Comment by thegeorgeous** [comment]
Not sure why this was closed as completed. Abandoned and broken packages and repos are still present and the list has gotten worse.

**Comment by savonarola** [comment]
The state of abandonment can be seen e.g. here: https://awsm-elixir.rubybox.dev/
Now most of the projects listed are abandoned.
Also this likely prevents users from adding there new projects here.

**Comment by simonewebdesign** [comment]
Anyone, please feel free to send a PR deleting anything that needs to be deleted. The resource above seems like a good reference to use for that.

**Comment by sonic182** [comment]
An interesting way of knowing the stars of the respos, is using the img.shields.io api, eg:

`[![Stars](https://img.shields.io/github/stars/sonic182/pub_subx)](https://github.com/sonic182/pub_subx/stargazers)
` ->

 [![Stars](https://img.shields.io/github/stars/sonic182/pub_subx)](https://github.com/sonic182/pub_subx/stargazers)

It can be added to each repo

**Comment by vegris** [comment]
Hello @simonewebdesign,

I’ve written a script that goes through all the GitHub repositories from a list and collects statistics about them.
You can find it here:
https://gist.github.com/vegris/1186dba49a0855fa557d1a3e12aed5cb

Essentially, it does the same thing as https://awsm-elixir.rubybox.dev/, but the output is machine-readable, and it also reports the status of the repository (deleted, archived, or available).

I’ve attached [projects.txt](https://github.com/user-attachments/files/18584327/projects.txt) with up-to-date information as of today, in case anyone wants to take a look at it but doesn’t want to run the script themselves.

Currently, the list includes 17 repositories that no longer exist and 47 that are archived. I’ll prepare a PR to remove the non-existent soon.

Regarding archived repositories and the mechanical approach of `if archived || commit_date < couple_years_ago || too_few_stars, do: remove()`, I have some doubts.

For example, the first archived repository on the list—[bloomex](https://github.com/gmcabrita/bloomex)—looks like a meaningful library with good documentation, 100% test coverage, and a version >= 1.0.0. According to the statistics on [Hex](https://hex.pm/packages/bloomex), this package is still being used by someone. The fact that the author has archived it only means that they will no longer maintain the code (update dependencies, accept PRs, or fix bugs) on their own. However, this doesn’t mean that the existing code is no longer useful. It can still provide value, and I personally don’t see anything wrong with keeping it in the awesome list.

Relying solely on the date of the last commit also doesn’t seem entirely justified to me. For instance, the [poolboy](https://github.com/devinus/poolboy) library was already removed from the list based on this criterion (commit: https://github.com/h4cc/awesome-elixir/pull/4859/commits/431f72100b94d4dbecb61aa266ec263751e02beb). Yet, this is a well-known library that is still widely used: it has over 100k weekly downloads on [Hex](https://hex.pm/packages/poolboy), and there are several articles about it, as seen in search results: [1](https://elixirschool.com/en/lessons/misc/poolboy), [2](https://samuelmullen.com/articles/elixir-poolboy-and-littles-law).

Instead, I would suggest to first mark archived or outdated libraries with specific labels. For example, 📚  for archived repositories and 📆 for those that haven’t seen a commit in several years. And only remove libraries later based on human judgment that they are hopelessly out of date/no longer needed.

Let me know your thoughts!

**Comment by vegris** [comment]
I went through the list of archived repositories and selected deleted most of them in #4899.

**Comment by simonewebdesign** [comment]
Amazing—thanks so much for all your contributions @vegris!
